added go tests to pipeline, initial commit
naps-dev/polarity pull request #9
Opened 2023-02-28 13:50 UTC by candreacchi

This is a draft PR to continue work on branch.  Still needs some work on figuring out the license input, which is currently expired so may limit amount of work able to be done.

2023-02-28 14:24 UTC, candreacchi commented
Failed as anticipated.  The Polarity Server pod is stuck in "init" since the license file wasn't properly provided or if it was somehow it is expired.  All other pods came up and are running.

2023-03-01 06:04 UTC, mikevanhemert requested changes

2023-03-01 06:12 UTC, mikevanhemert commented on .github/workflows/package.yaml
> +          go test
Late breaking news! As long as this child action includes an env BRANCH_NAME definition like [this line in Arkime](https://github.com/naps-dev/arkime/blob/sensor/.github/workflows/package.yaml#L22) it is gtg!

2023-03-01 16:17 UTC, Vandiver247 commented on .github/workflows/package.yaml
> +  ZARF_S3_PATH: "s3://${{ secrets.AWS_BUCKET }}/${{ github.repository }}/${{ github.head_ref || github.ref_name }}"
As discussed this morning, will update in future PR

2023-03-01 16:29 UTC, Vandiver247 commented on .github/workflows/package.yaml
> +          go test
Updated.

2023-03-01 16:29 UTC, Vandiver247 commented on .github/workflows/main.yaml
> +  S3_PATH: "s3://${{ secrets.AWS_BUCKET }}/${{ github.repository }}/${{ github.head_ref || github.ref_name }}"
Removed

2023-03-01 16:29 UTC, merged